package reman.client.app.finance.equations.exceptions;

/**
 * This class provides a base class for all exceptions generated by the equation engine.
 * @author Scott
 *
 */
public class MathException extends Exception{

	public MathException(String message)
	{
		super(message);
	}
}
